version: '3.1'

services:
  mongo:
    image: mongo
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    #restart: always
    depends_on:
      - mongo
  mongo-node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes: 
    - ./node-api:/src
    - /src/node_modules
    depends_on:
      - mongo
      - mongo-express
  mongo-node-ui:
    build:
      context: ./node-ui
      dockerfile: Dockerfile
      target: run
    ports:
      - 7878:80
   # restart: always
    volumes: 
    - ./node-ui:/app
    - /app/node_modules
    depends_on:
      - mongo
      - mongo-node-api